# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'leandesign' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
inhibit_all_warnings!

  # Pods for leandesign
pod 'Fabric'
pod 'Digits'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'
pod 'DKImagePickerController'
pod 'PullToRefresher', '~> 1.4.0'
pod 'Swiftstraints'
pod 'HanekeSwift'
pod 'OneSignal'

end
